CREATE TABLE IF NOT EXISTS office_forms (
  id SERIAL PRIMARY KEY,
  transaction_id INTEGER REFERENCES transactions(id) ON DELETE CASCADE,
  las_sellers TEXT,
  las_address TEXT,
  las_mls_number TEXT,
  las_showing_times TEXT,
  las_lockbox_number TEXT,
  las_shackle_code TEXT,
  las_showing_notes TEXT,
  las_doc_listing_contract BOOLEAN DEFAULT FALSE,
  las_doc_data_input BOOLEAN DEFAULT FALSE,
  las_doc_fintrac BOOLEAN DEFAULT FALSE,
  las_doc_title_search BOOLEAN DEFAULT FALSE,
  las_doc_rpr BOOLEAN DEFAULT FALSE,
  las_doc_crg BOOLEAN DEFAULT FALSE,
  las_doc_condo BOOLEAN DEFAULT FALSE,
  las_act_photos_complete BOOLEAN DEFAULT FALSE,
  las_act_photos_date DATE,
  las_act_sign_complete BOOLEAN DEFAULT FALSE,
  las_act_sign_date DATE,
  las_act_justlisted_complete BOOLEAN DEFAULT FALSE,
  las_act_justlisted_date DATE,
  las_act_lockbox_complete BOOLEAN DEFAULT FALSE,
  las_act_lockbox_date DATE,
  las_act_openhouse_complete BOOLEAN DEFAULT FALSE,
  las_act_openhouse_date DATE,
  las_act_featuresheet_complete BOOLEAN DEFAULT FALSE,
  las_act_featuresheet_date DATE,
  las_act_virtualtour_complete BOOLEAN DEFAULT FALSE,
  las_act_virtualtour_date DATE,
  las_act_socialmedia_complete BOOLEAN DEFAULT FALSE,
  las_act_socialmedia_date DATE,
  las_rpr_ordered_date DATE,
  las_rpr_received_date DATE,
  las_update_call_1 DATE,
  las_update_call_2 DATE,
  las_update_call_3 DATE,
  las_update_call_4 DATE,
  las_update_call_5 DATE,
  las_update_call_6 DATE,
  brf_purchaser_name_print TEXT,
  brf_date DATE,
  brf_purchaser_name TEXT,
  brf_purchaser_address TEXT,
  brf_business_phone TEXT,
  brf_residence_phone TEXT,
  brf_realtor_name_print TEXT,
  brf_community_project TEXT,
  brf_realtor_name TEXT,
  brf_brokerage_address TEXT,
  brf_brokerage_phone TEXT,
  brf_realtor_cell TEXT,
  brf_new_home_interests TEXT,
  brf_commission TEXT,
  brf_special_terms TEXT,
  brf_expiry_date DATE,
  brf_commission_payout TEXT,
  brf_builder_sig_date DATE,
  can_listing_id TEXT,
  can_sale_price NUMERIC,
  can_seller_name TEXT,
  can_property_address TEXT,
  can_originally_sold_date DATE,
  can_reason_courts BOOLEAN DEFAULT FALSE,
  can_reason_death BOOLEAN DEFAULT FALSE,
  can_reason_deposit BOOLEAN DEFAULT FALSE,
  can_reason_finance BOOLEAN DEFAULT FALSE,
  can_reason_lawyer BOOLEAN DEFAULT FALSE,
  can_reason_noncompliance BOOLEAN DEFAULT FALSE,
  can_reason_regsub BOOLEAN DEFAULT FALSE,
  can_reason_error_other BOOLEAN DEFAULT FALSE,
  can_reason_withdrawal BOOLEAN DEFAULT FALSE,
  can_listing_firm TEXT,
  can_branch_number TEXT,
  can_dated DATE,
  can_approved_by TEXT,
  eft_bank_name TEXT,
  eft_bank_branch TEXT,
  eft_bank_address TEXT,
  eft_bank_city TEXT,
  eft_bank_province TEXT,
  eft_bank_postal_code TEXT,
  eft_account_holder TEXT,
  eft_account_number TEXT,
  eft_transit_number TEXT,
  eft_institution_number TEXT,
  eft_amount NUMERIC,
  eft_reference TEXT,
  eft_date DATE,
  eft_signature TEXT,
  eft_print_name TEXT,
  eft_signature_date DATE,
  lst_sellers TEXT,
  lst_price NUMERIC,
  lst_transaction_address TEXT,
  lst_zone TEXT,
  lst_mailing_address TEXT,
  lst_city TEXT,
  lst_client_phone TEXT,
  lst_email TEXT,
  lst_postal_code TEXT,
  lst_agent TEXT,
  lst_relist TEXT,
  lst_list_date DATE,
  lst_expiry_date DATE,
  lst_mls_number TEXT,
  lst_doc_sra BOOLEAN DEFAULT FALSE,
  lst_doc_mls_sheet BOOLEAN DEFAULT FALSE,
  lst_doc_fintrac BOOLEAN DEFAULT FALSE,
  lst_doc_land_title BOOLEAN DEFAULT FALSE,
  lst_doc_crg BOOLEAN DEFAULT FALSE,
  lst_doc_rms BOOLEAN DEFAULT FALSE,
  lst_vacant_hh_yes BOOLEAN DEFAULT FALSE,
  lst_vacant_hh_no BOOLEAN DEFAULT FALSE,
  lst_covid_hh_yes BOOLEAN DEFAULT FALSE,
  lst_covid_hh_no BOOLEAN DEFAULT FALSE,
  lst_order_lt_yes BOOLEAN DEFAULT FALSE,
  lst_order_lt_no BOOLEAN DEFAULT FALSE,
  lst_colb_yes BOOLEAN DEFAULT FALSE,
  lst_colb_no BOOLEAN DEFAULT FALSE,
  lst_sign_new BOOLEAN DEFAULT FALSE,
  lst_sign_move BOOLEAN DEFAULT FALSE,
  lst_sign_remove BOOLEAN DEFAULT FALSE,
  lst_sign_notes TEXT,
  lst_social_media BOOLEAN DEFAULT FALSE,
  lst_social_media_notes TEXT,
  lst_additional_instructions TEXT,
  lst_admin_notes TEXT,
  lst_admin_completed_by TEXT,
  lst_admin_date DATE,
  ref_referred_date DATE,
  ref_type_buy BOOLEAN DEFAULT FALSE,
  ref_type_list BOOLEAN DEFAULT FALSE,
  ref_property_address TEXT,
  ref_from_name TEXT,
  ref_from_address TEXT,
  ref_from_city TEXT,
  ref_from_province TEXT,
  ref_from_postal_code TEXT,
  ref_from_phone TEXT,
  ref_from_email TEXT,
  ref_to_office_address TEXT,
  ref_to_office_city TEXT,
  ref_to_realtor TEXT,
  ref_to_email TEXT,
  ref_person_name TEXT,
  ref_person_address TEXT,
  ref_person_city TEXT,
  ref_person_province TEXT,
  ref_person_postal_code TEXT,
  ref_person_email TEXT,
  ref_person_phone1 TEXT,
  ref_person_phone2 TEXT,
  ref_percent TEXT,
  ref_fixed_amount NUMERIC,
  ref_referrer_sig_date DATE,
  ref_agent_sig_date DATE,
  ptd_agent_name TEXT,
  ptd_property_address TEXT,
  ptd_decl_purchasing BOOLEAN DEFAULT FALSE,
  ptd_decl_selling BOOLEAN DEFAULT FALSE,
  ptd_decl_family_purchasing BOOLEAN DEFAULT FALSE,
  ptd_decl_family_selling BOOLEAN DEFAULT FALSE,
  ptd_decl_other BOOLEAN DEFAULT FALSE,
  ptd_rep_item1 TEXT,
  ptd_rep_item2 TEXT,
  ptd_rep_item3 TEXT,
  ptd_rep_item4 TEXT,
  ptd_rep_item5 TEXT,
  ptd_agent_initials TEXT,
  ptd_forfeit_commission BOOLEAN DEFAULT FALSE,
  ptd_waive_deal_fee BOOLEAN DEFAULT FALSE,
  ptd_broker_item1 BOOLEAN DEFAULT FALSE,
  ptd_broker_item2 BOOLEAN DEFAULT FALSE,
  ptd_broker_item3 BOOLEAN DEFAULT FALSE,
  ptd_broker_item4 BOOLEAN DEFAULT FALSE,
  ptd_broker_notes TEXT,
  ptd_broker_sig_date DATE,
  ptd_agent_sig_date DATE,
  nar_first_name TEXT,
  nar_last_name TEXT,
  nar_email TEXT,
  nar_phone TEXT,
  nar_cell_phone TEXT,
  nar_address TEXT,
  nar_city TEXT,
  nar_province TEXT,
  nar_postal_code TEXT,
  nar_license_number TEXT,
  nar_license_expiry DATE,
  nar_eo_policy TEXT,
  nar_prev_brokerage TEXT,
  nar_prev_broker TEXT,
  nar_prev_broker_phone TEXT,
  nar_start_date DATE,
  nar_team_name TEXT,
  nar_notes TEXT,
  tts_realtor_name TEXT,
  tts_date DATE,
  tts_property_address TEXT,
  tts_lt_plan TEXT,
  tts_lt_block_unit TEXT,
  tts_lt_lot TEXT,
  tts_lt_linc TEXT,
  tts_rt_meridian TEXT,
  tts_rt_range TEXT,
  tts_rt_township TEXT,
  tts_rt_section TEXT,
  tts_rt_quarter TEXT,
  tts_condo_plan TEXT,
  tis_conditional_deal BOOLEAN DEFAULT FALSE,
  tis_firm_deal BOOLEAN DEFAULT FALSE,
  tis_address TEXT,
  tis_city TEXT,
  tis_postal_code TEXT,
  tis_plan TEXT,
  tis_block_unit TEXT,
  tis_lot TEXT,
  tis_mls_number TEXT,
  tis_sale_price NUMERIC,
  tis_listing_price NUMERIC,
  tis_initial_deposit NUMERIC,
  tis_additional_deposit NUMERIC,
  tis_deposit_held_by TEXT,
  tis_possession_date DATE,
  tis_binding_date DATE,
  tis_condition_removal_date DATE,
  tis_sign_removal_date DATE,
  tis_listing_brokerage TEXT,
  tis_listing_agent TEXT,
  tis_listing_office_phone TEXT,
  tis_listing_office_address TEXT,
  tis_listing_office_city TEXT,
  tis_listing_office_postal TEXT,
  tis_buyer_brokerage TEXT,
  tis_buyer_agent TEXT,
  tis_buyer_office_phone TEXT,
  tis_buyer_office_address TEXT,
  tis_buyer_office_city TEXT,
  tis_buyer_office_postal TEXT,
  tis_vendor_name1 TEXT,
  tis_vendor_name2 TEXT,
  tis_vendor_address TEXT,
  tis_vendor_city TEXT,
  tis_vendor_postal TEXT,
  tis_vendor_phone TEXT,
  tis_vendor_email TEXT,
  tis_purchaser_name1 TEXT,
  tis_purchaser_name2 TEXT,
  tis_purchaser_address TEXT,
  tis_purchaser_city TEXT,
  tis_purchaser_postal TEXT,
  tis_purchaser_phone TEXT,
  tis_purchaser_email TEXT,
  tis_vendor_lawyer_name TEXT,
  tis_vendor_lawyer_firm TEXT,
  tis_vendor_lawyer_address TEXT,
  tis_vendor_lawyer_city TEXT,
  tis_vendor_lawyer_postal TEXT,
  tis_vendor_lawyer_phone TEXT,
  tis_vendor_lawyer_email TEXT,
  tis_purchaser_lawyer_name TEXT,
  tis_purchaser_lawyer_firm TEXT,
  tis_purchaser_lawyer_address TEXT,
  tis_purchaser_lawyer_city TEXT,
  tis_purchaser_lawyer_postal TEXT,
  tis_purchaser_lawyer_phone TEXT,
  tis_purchaser_lawyer_email TEXT,
  tis_listing_ref_brokerage TEXT,
  tis_listing_ref_agent TEXT,
  tis_listing_ref_address TEXT,
  tis_listing_ref_city TEXT,
  tis_listing_ref_postal TEXT,
  tis_listing_ref_phone TEXT,
  tis_listing_ref_email TEXT,
  tis_buying_ref_brokerage TEXT,
  tis_buying_ref_agent TEXT,
  tis_buying_ref_address TEXT,
  tis_buying_ref_city TEXT,
  tis_buying_ref_postal TEXT,
  tis_buying_ref_phone TEXT,
  tis_buying_ref_email TEXT,
  tis_total_commission TEXT,
  tis_commission_listing_pct TEXT,
  tis_commission_buying_pct TEXT,
  tis_new_home BOOLEAN DEFAULT FALSE,
  tis_based_net_gst BOOLEAN DEFAULT FALSE,
  tis_source_of_business TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS fintrac_records (
  id SERIAL PRIMARY KEY,
  transaction_id INTEGER REFERENCES transactions(id) ON DELETE CASCADE,
  entity_name TEXT,
  directors_names TEXT,
  trustees_names TEXT,
  trust_entity_trustees TEXT,
  entity_owners_25pct TEXT,
  share_owners_25pct TEXT,
  unit_owners_25pct TEXT,
  ownership_structure TEXT,
  is_registered_charity TEXT,
  solicits_donations TEXT,
  asked_entity_info BOOLEAN DEFAULT FALSE,
  has_minute_book BOOLEAN DEFAULT FALSE,
  has_shareholders_register BOOLEAN DEFAULT FALSE,
  has_annual_returns BOOLEAN DEFAULT FALSE,
  has_shareholder_agreement BOOLEAN DEFAULT FALSE,
  has_board_records BOOLEAN DEFAULT FALSE,
  has_trust_deed BOOLEAN DEFAULT FALSE,
  has_securities_register BOOLEAN DEFAULT FALSE,
  has_articles_incorporation BOOLEAN DEFAULT FALSE,
  has_cert_corporate_status BOOLEAN DEFAULT FALSE,
  has_partnership_agreement BOOLEAN DEFAULT FALSE,
  accuracy_other_explain TEXT,
  checked_cra_charities BOOLEAN DEFAULT FALSE,
  accuracy_internet_search BOOLEAN DEFAULT FALSE,
  entity_signed_letter BOOLEAN DEFAULT FALSE,
  confirm_other_explain TEXT,
  measures_date DATE,
  verified_ceo_identity BOOLEAN DEFAULT FALSE,
  applied_special_measures BOOLEAN DEFAULT FALSE,
  brokerage_name TEXT,
  compliance_officer TEXT,
  date_completed DATE,
  completed_by TEXT,
  property_address TEXT,
  rep_name TEXT,
  record_date DATE,
  corporation_name TEXT,
  corporate_address TEXT,
  principal_business TEXT,
  director_names TEXT,
  verification_record_type TEXT,
  verification_source TEXT,
  corp_registration_number TEXT,
  corp_records_attached BOOLEAN DEFAULT FALSE,
  other_entity_name TEXT,
  other_entity_address TEXT,
  other_entity_business TEXT,
  other_entity_verification_type TEXT,
  other_entity_record_source TEXT,
  other_entity_reg_number TEXT,
  has_third_party TEXT,
  third_party_reason TEXT,
  third_party_name TEXT,
  third_party_address TEXT,
  third_party_phone TEXT,
  third_party_dob DATE,
  third_party_occupation TEXT,
  third_party_reg_number TEXT,
  third_party_relationship TEXT,
  risk_q1_previous_client TEXT,
  risk_q2_criminal_history TEXT,
  risk_q3_geographic_concern TEXT,
  risk_q4_border_proximity TEXT,
  risk_q5_canadian_corp TEXT,
  risk_q6_ministerial_directive TEXT,
  risk_q7_high_risk_country TEXT,
  risk_q8_concealed_identity TEXT,
  risk_q9_previous_str TEXT,
  risk_q10_unusual_transaction TEXT,
  risk_q11_third_party TEXT,
  risk_q12_non_face_to_face TEXT,
  risk_q13_cash_deposit TEXT,
  risk_q14_unusual_past TEXT,
  risk_q15_shell_company TEXT,
  risk_q16_cash_intensive TEXT,
  risk_q17_other_unusual TEXT,
  total_risk_score NUMERIC,
  business_purpose TEXT,
  business_purpose_other TEXT,
  business_dealings_desc TEXT,
  monitoring_measures TEXT,
  enhanced_measures TEXT,
  brokerage_address TEXT,
  agent_name TEXT,
  agent_address TEXT,
  effective_day TEXT,
  effective_year TEXT,
  compensation_details TEXT,
  execution_day TEXT,
  execution_month TEXT,
  execution_year TEXT,
  broker_signature TEXT,
  broker_sign_date DATE,
  agent_signature TEXT,
  agent_sign_date DATE,
  individuals_to_identify TEXT,
  corps_to_identify TEXT,
  date_info_received DATE,
  date_info_referred DATE,
  method_photo_id BOOLEAN DEFAULT FALSE,
  method_credit_file BOOLEAN DEFAULT FALSE,
  method_dual_id BOOLEAN DEFAULT FALSE,
  date_verified DATE,
  individual_name TEXT,
  individual_address TEXT,
  individual_dob DATE,
  individual_occupation TEXT,
  id_type TEXT,
  id_type_other TEXT,
  id_number TEXT,
  id_jurisdiction TEXT,
  id_country TEXT,
  id_expiry DATE,
  credit_bureau_name TEXT,
  credit_file_ref TEXT,
  dual_id_name_dob BOOLEAN DEFAULT FALSE,
  dual_id_dob_source TEXT,
  dual_id_dob_account TEXT,
  dual_id_name_address BOOLEAN DEFAULT FALSE,
  dual_id_addr_source TEXT,
  dual_id_addr_account TEXT,
  dual_id_name_account BOOLEAN DEFAULT FALSE,
  dual_id_fin_source TEXT,
  dual_id_fin_acct_type TEXT,
  dual_id_fin_acct_num TEXT,
  risk_q5_canadian_citizen TEXT,
  risk_q6_domestic_pep TEXT,
  risk_q7_foreign_pep TEXT,
  risk_q8_ministerial_directive TEXT,
  risk_q9_high_risk_country TEXT,
  risk_q10_concealed_identity TEXT,
  risk_q11_previous_str TEXT,
  risk_q12_unusual_transaction TEXT,
  risk_q13_third_party TEXT,
  risk_q14_non_face_to_face TEXT,
  risk_q15_cash_deposit TEXT,
  risk_q16_unusual_past TEXT,
  pep_individual_name TEXT,
  is_foreign_pep BOOLEAN DEFAULT FALSE,
  is_domestic_pep BOOLEAN DEFAULT FALSE,
  is_hio BOOLEAN DEFAULT FALSE,
  pep_none_above BOOLEAN DEFAULT FALSE,
  pep_method_asked BOOLEAN DEFAULT FALSE,
  pep_method_internet BOOLEAN DEFAULT FALSE,
  pep_method_database BOOLEAN DEFAULT FALSE,
  pep_method_other TEXT,
  pep_determination_date DATE,
  pep_position TEXT,
  pep_organization TEXT,
  pep_domestic_high_risk TEXT,
  pep_source_wealth TEXT,
  pep_enhanced_measures_verified BOOLEAN DEFAULT FALSE,
  pep_100k_high_risk TEXT,
  pep_100k_source_cash TEXT,
  pep_100k_source_wealth TEXT,
  pep_100k_mgmt_reviewer TEXT,
  pep_100k_review_date DATE,
  funds1_amount TEXT,
  funds1_currency TEXT,
  funds1_date DATE,
  funds1_type TEXT,
  funds1_type_other TEXT,
  funds1_method TEXT,
  funds1_method_other TEXT,
  funds1_purpose TEXT,
  funds1_exchange_rate TEXT,
  funds1_exchange_source TEXT,
  funds2_amount TEXT,
  funds2_currency TEXT,
  funds2_date DATE,
  funds2_type TEXT,
  funds2_type_other TEXT,
  funds2_method TEXT,
  funds2_method_other TEXT,
  funds2_purpose TEXT,
  funds2_exchange_rate TEXT,
  funds2_exchange_source TEXT,
  funds3_amount TEXT,
  funds3_currency TEXT,
  funds3_date DATE,
  funds3_type TEXT,
  funds3_type_other TEXT,
  funds3_method TEXT,
  funds3_method_other TEXT,
  funds3_purpose TEXT,
  funds3_exchange_rate TEXT,
  funds3_exchange_source TEXT,
  brokerage_ref_number TEXT,
  account1_number TEXT,
  account1_holder TEXT,
  account1_type TEXT,
  account1_type_other TEXT,
  account2_number TEXT,
  account2_holder TEXT,
  account2_type TEXT,
  account2_type_other TEXT,
  funder_name TEXT,
  funder_address TEXT,
  funder_dob DATE,
  funder_occupation TEXT,
  funder_date_verified DATE,
  funder_id_type TEXT,
  funder_id_type_other TEXT,
  funder_id_number TEXT,
  funder_id_jurisdiction TEXT,
  funder_id_country TEXT,
  funder_id_expiry DATE,
  funder_credit_bureau TEXT,
  funder_credit_ref TEXT,
  funder_dual_dob_source TEXT,
  funder_dual_dob_account TEXT,
  funder_dual_addr_source TEXT,
  funder_dual_addr_account TEXT,
  funder_dual_fin_source TEXT,
  funder_dual_fin_type TEXT,
  funder_dual_fin_account TEXT,
  funder_corp_name TEXT,
  funder_corp_address TEXT,
  funder_corp_business TEXT,
  funder_corp_verification_type TEXT,
  funder_corp_verification_source TEXT,
  funder_corp_directors TEXT,
  funder_corp_reg_number TEXT,
  funder_corp_records_attached BOOLEAN DEFAULT FALSE,
  funder_entity_reg_number TEXT,
  other_person_name TEXT,
  other_person_address TEXT,
  other_person_dob DATE,
  other_person_occupation TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

